// Shared helpers for the static build.
// The site is served at www (GoDaddy DNS: www → Cloudflare Pages; the bare domain forwards to www).
export const SITE = 'https://www.weareinfinit.com';
export const LANGS = ['en', 'ca', 'es'];
export const LOCALE = { en: 'en_GB', ca: 'ca_ES', es: 'es_ES' };
export const EMAIL = 'hello@weareinfinit.com';
export const PHONE = '+34 689 022 383';
export const LINKEDIN = 'https://www.linkedin.com/company/weareinfinit/';
export const INSTAGRAM = 'https://www.instagram.com/weareinfinit.studio/';

// Page routes (same slug in every language).
export const ROUTES = {
  home: '',
  studio: 'studio/',
  bunnker: 'work/bunnker/',
  relats: 'work/relats/',
  industrial: 'industrial-branding/',
  automotive: 'automotive-branding/',
  food: 'food-branding/',
  pharma: 'pharma-branding/',
  realestate: 'real-estate-branding/',
  tech: 'tech-branding/',
  family: 'family-business-branding/',
  international: 'international-branding/',
  sectors: 'sectors/',
  fashion: 'fashion-branding/',
  energy: 'energy-branding/',
  leisure: 'outdoor-leisure-branding/',
  mergers: 'merger-acquisition-branding/',
  launch: 'brand-launch/',
  employer: 'employer-branding/',
  website: 'b2b-website-design/',
  geo: 'geo-ai-search/',
  cmo: 'fractional-cmo/',
  workidx: 'work/',
  journal: 'journal/',
  // Journal articles ("j:<slug>") are added by jdata.mjs.
};
// Social image file name for a page key ("j:<slug>" → "j-<slug>"), see og.mjs.
export const ogName = page => page.replace(':', '-');
export const url = (lang, page) => `/${lang}/${ROUTES[page]}`;
export const abs = (lang, page) => SITE + url(lang, page);

// Escape text for HTML.
export const esc = s => String(s).replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
// Root-relative asset URL with each path segment encoded ("Bunnker Final.webp" → "Bunnker%20Final.webp").
export const A = p => '/' + p.split('/').map(encodeURIComponent).join('/');

// Service colour system (oklch, subtle).
export const dot = h => `oklch(.72 .05 ${h})`;
export const tint = h => `oklch(.92 .025 ${h})`;

// The INFINIT© wordmark as inline SVG outlines (Geist 900 + © in Geist 500), generated by .site/wordmark.mjs.
// 'fit' fills the container width; a number is the type size in px (as in the prototype: © at .2em above 80px, .42em below).
import { readFileSync } from 'node:fs';
const WM = JSON.parse(readFileSync(new URL('./wordmark.json', import.meta.url)));
// The bold © (handoff v3.1): ring r 13.2 + C arc r 6 opening right, stroke 3.3, in a 32×32 box. It replaces the
// Geist © glyph — drawn in the glyph's place, its outer edge on the glyph's bounding box.
export const MARK_SVG = '<circle cx="16" cy="16" r="13.2"/><path d="M20.46 11.99A6 6 0 1 0 20.46 20.01"/>';
const boldC = c => {
  const n = c.match(/-?\d+(?:\.\d+)?/g).map(Number), xs = n.filter((_, i) => i % 2 === 0), ys = n.filter((_, i) => i % 2 === 1);
  const x0 = Math.min(...xs), x1 = Math.max(...xs), y0 = Math.min(...ys), y1 = Math.max(...ys);
  const k = Math.max(x1 - x0, y1 - y0) / (2 * (13.2 + 3.3 / 2)), cx = (x0 + x1) / 2, cy = (y0 + y1) / 2;
  const P = (x, y) => `${(cx + (x - 16) * k).toFixed(2)} ${(cy + (y - 16) * k).toFixed(2)}`, r = v => (v * k).toFixed(2);
  return `<g class="c" fill="none" stroke="currentColor" stroke-width="${r(3.3)}"><circle cx="${cx.toFixed(2)}" cy="${cy.toFixed(2)}" r="${r(13.2)}"/><path d="M${P(20.46, 11.99)}A${r(6)} ${r(6)} 0 1 0 ${P(20.46, 20.01)}"/></g>`;
};
const BOLD = { lg: boldC(WM.lg.c), sm: boldC(WM.sm.c) };
export const wm = (size) => {
  const v = size === 'fit' || size > 80 ? WM.lg : WM.sm, bc = v === WM.lg ? BOLD.lg : BOLD.sm;
  const style = size === 'fit' ? '' : ` style="height:${(size * WM.h / 100).toFixed(2)}px"`;
  return `<svg class="wm${size === 'fit' ? ' wm-fit' : ''}" viewBox="0 ${WM.top} ${v.w} ${WM.h}" aria-hidden="true" focusable="false"${style}>${WM.letters.map(d => `<path d="${d}"/>`).join('')}${bc}</svg>`;
};

// width/height attributes for a PNG shown at height h (reserves its box before it loads).
export const pngDim = (rel, h) => {
  const b = readFileSync(new URL('../' + rel, import.meta.url)), w = b.readUInt32BE(16), ht = b.readUInt32BE(20);
  return ` width="${Math.round(h * w / ht)}" height="${h}"`;
};

export const ARROW_X = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" aria-hidden="true"><path d="M6 6l12 12M18 6L6 18"/></svg>';
