// Shared helpers for the static build.
// The site is served at www (GoDaddy DNS: www → Cloudflare Pages; the bare domain forwards to www).
export const SITE = 'https://www.weareinfinit.com';
export const LANGS = ['en', 'ca', 'es'];
export const LOCALE = { en: 'en_GB', ca: 'ca_ES', es: 'es_ES' };
export const EMAIL = 'hello@weareinfinit.com';
export const PHONE = '+34 689 022 383';
export const LINKEDIN = 'https://www.linkedin.com/company/weareinfinit/';
export const INSTAGRAM = 'https://www.instagram.com/weareinfinit.studio/';

// Page routes (same slug in every language).
export const ROUTES = {
  home: '',
  studio: 'studio/',
  bunnker: 'work/bunnker/',
  relats: 'work/relats/',
  industrial: 'industrial-branding/',
  automotive: 'automotive-branding/',
  food: 'food-branding/',
  pharma: 'pharma-branding/',
  realestate: 'real-estate-branding/',
  tech: 'tech-branding/',
  family: 'family-business-branding/',
  international: 'international-branding/',
  sectors: 'sectors/',
  fashion: 'fashion-branding/',
  energy: 'energy-branding/',
  leisure: 'outdoor-leisure-branding/',
  mergers: 'merger-acquisition-branding/',
  launch: 'brand-launch/',
  employer: 'employer-branding/',
  website: 'b2b-website-design/',
  geo: 'geo-ai-search/',
  cmo: 'fractional-cmo/',
};
export const url = (lang, page) => `/${lang}/${ROUTES[page]}`;
export const abs = (lang, page) => SITE + url(lang, page);

// Escape text for HTML.
export const esc = s => String(s).replace(/[&<>"]/g, c => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;' }[c]));
// Root-relative asset URL with each path segment encoded ("Bunnker Final.webp" → "Bunnker%20Final.webp").
export const A = p => '/' + p.split('/').map(encodeURIComponent).join('/');

// Service colour system (oklch, subtle).
export const dot = h => `oklch(.72 .05 ${h})`;
export const tint = h => `oklch(.92 .025 ${h})`;

// The INFINIT© wordmark as inline SVG outlines (Geist 900 + © in Geist 500), generated by .site/wordmark.mjs.
// 'fit' fills the container width; a number is the type size in px (as in the prototype: © at .2em above 80px, .42em below).
import { readFileSync } from 'node:fs';
const WM = JSON.parse(readFileSync(new URL('./wordmark.json', import.meta.url)));
export const wm = (size) => {
  const v = size === 'fit' || size > 80 ? WM.lg : WM.sm;
  const style = size === 'fit' ? '' : ` style="height:${(size * WM.h / 100).toFixed(2)}px"`;
  return `<svg class="wm${size === 'fit' ? ' wm-fit' : ''}" viewBox="0 ${WM.top} ${v.w} ${WM.h}" aria-hidden="true" focusable="false"${style}>${WM.letters.map(d => `<path d="${d}"/>`).join('')}<path class="c" d="${v.c}"/></svg>`;
};

// width/height attributes for a PNG shown at height h (reserves its box before it loads).
export const pngDim = (rel, h) => {
  const b = readFileSync(new URL('../' + rel, import.meta.url)), w = b.readUInt32BE(16), ht = b.readUInt32BE(20);
  return ` width="${Math.round(h * w / ht)}" height="${h}"`;
};

export const ARROW_X = '<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" aria-hidden="true"><path d="M6 6l12 12M18 6L6 18"/></svg>';
